#pragma once

#include "resource.h"

typedef enum {
	MAP_OVERVIEW_LAYER = ID_LAYER_MAPOVERVIEW,
	MAP_LAYER = ID_LAYER_MAP,
	OBJECT_LAYER = ID_LAYER_OBJECT,
	ENEMY_LAYER = ID_LAYER_ENEMY,
	MISC_LAYER = ID_LAYER_MISC,
	START_LAYER = ID_LAYER_STARTLOCATIONS,
	NO_LAYER = -1,
} LAYER;

void SetEditorLayer(LAYER layer);