#include "core.h"

//alu
void no_reverse_info(CPU_t *cpu);
void adc_hl_reg16_reverse_info(CPU_t *cpu);
void sbc_hl_reg16_reverse_info(CPU_t *cpu);
void rld_reverse_info(CPU_t *cpu);
void rrd_reverse_info(CPU_t *cpu);
void res_reverse_info(CPU_t *cpu);
void set_reverse_info(CPU_t *cpu);
void rl_reg_reverse_info(CPU_t *cpu);
void rlc_reg_reverse_info(CPU_t *cpu);
void rr_reg_reverse_info(CPU_t *cpu);
void rrc_reg_reverse_info(CPU_t *cpu);
void sll_reg_reverse_info(CPU_t *cpu);
void sla_reg_reverse_info(CPU_t *cpu);
void sra_reg_reverse_info(CPU_t *cpu);
void srl_reg_reverse_info(CPU_t *cpu);
void and_reg8_reverse_info(CPU_t *cpu);
void and_num8_reverse_info(CPU_t *cpu);
void or_reg8_reverse_info(CPU_t *cpu);
void or_num8_reverse_info(CPU_t *cpu);
void xor_reg8_reverse_info(CPU_t *cpu);
void xor_num8_reverse_info(CPU_t *cpu);
void cpl_reverse_info(CPU_t *cpu);
void daa_reverse_info(CPU_t *cpu);
void adc_a_reg8_reverse_info(CPU_t *cpu);
void add_a_reg8_reverse_info(CPU_t *cpu);
void adc_a_num8_reverse_info(CPU_t *cpu);
void add_a_num8_reverse_info(CPU_t *cpu);
void sbc_a_reg8_reverse_info(CPU_t *cpu);
void sub_a_reg8_reverse_info(CPU_t *cpu);
void sbc_a_num8_reverse_info(CPU_t *cpu);
void sub_a_num8_reverse_info(CPU_t *cpu);
void add_hl_reg16_reverse_info(CPU_t *cpu);
void rla_reverse_info(CPU_t *cpu);
void rlca_reverse_info(CPU_t *cpu);
void rra_reverse_info(CPU_t *cpu);
void rrca_reverse_info(CPU_t *cpu);
//control
void ldd_reverse_info(CPU_t *cpu);
void lddr_reverse_info(CPU_t *cpu);
void ldi_reverse_info(CPU_t *cpu);
void ldir_reverse_info(CPU_t *cpu);
void ld_mem16_reg16_reverse_info(CPU_t *cpu);
void ld_reg16_mem16_reverse_info(CPU_t *cpu);
void IM0_reverse_info(CPU_t *cpu);
void IM1_reverse_info(CPU_t *cpu);
void IM2_reverse_info(CPU_t *cpu);
void ind_reverse_info(CPU_t *cpu);
void indr_reverse_info(CPU_t *cpu);
void ini_reverse_info(CPU_t *cpu);
void inir_reverse_info(CPU_t *cpu);
void ld_i_a_reverse_info(CPU_t *cpu);
void ld_r_a_reverse_info(CPU_t *cpu);
void ld_a_i_reverse_info(CPU_t *cpu);
void ld_a_r_reverse_info(CPU_t *cpu);
void reti_reverse_info(CPU_t *cpu);
void retn_reverse_info(CPU_t *cpu);
void rst_reverse_info(CPU_t *cpu);
void in_reverse_info(CPU_t *cpu);
void ret_reverse_info(CPU_t *cpu);
void ret_condition_reverse_info(CPU_t *cpu);
void call_reverse_info(CPU_t *cpu);
void call_condition_reverse_info(CPU_t *cpu);
void push_reg16_reverse_info(CPU_t *cpu);
void pop_reg16_reverse_info(CPU_t *cpu);
void ld_sp_hl_reverse_info(CPU_t *cpu);
void ld_mem16_hlf_reverse_info(CPU_t *cpu);
void ld_hlf_mem16_reverse_info(CPU_t *cpu);
void ld_hl_num16_reverse_info(CPU_t *cpu);
void ld_de_num16_reverse_info(CPU_t *cpu);
void ld_bc_num16_reverse_info(CPU_t *cpu);
void ld_sp_num16_reverse_info(CPU_t *cpu);
void ld_a_mem16_reverse_info(CPU_t *cpu);
void ld_a_bc_reverse_info(CPU_t *cpu);
void ld_a_de_reverse_info(CPU_t *cpu);
void ld_mem16_a_reverse_info(CPU_t *cpu);
void ld_bc_a_reverse_info(CPU_t *cpu);
void ld_de_a_reverse_info(CPU_t *cpu);
void ld_r_num8_reverse_info(CPU_t *cpu);
void ld_r_r_reverse_info(CPU_t *cpu);
void halt_reverse_info(CPU_t *cpu);
void jp_hl_reverse_info(CPU_t *cpu);
void jp_reverse_info(CPU_t *cpu);
void jp_condition_reverse_info(CPU_t *cpu);
void jr_condition_reverse_info(CPU_t *cpu) ;
void jr_reverse_info(CPU_t *cpu);
void djnz_reverse_info(CPU_t *cpu);
void ei_reverse_info(CPU_t *cpu);
void di_reverse_info(CPU_t *cpu);
//indexcb
void no_reverse_cb_info(CPU_t *cpu, char offset);
void res_ind_reverse_info(CPU_t *cpu, char offset);
void set_ind_reverse_info(CPU_t *cpu, char offset);
void rl_ind_reverse_info(CPU_t *cpu, char offset);
void rlc_ind_reverse_info(CPU_t *cpu, char offset);
void rr_ind_reverse_info(CPU_t *cpu, char offset);
void rrc_ind_reverse_info(CPU_t *cpu, char offset);
void sll_ind_reverse_info(CPU_t *cpu, char offset);
void srl_ind_reverse_info(CPU_t *cpu, char offset);
void sla_ind_reverse_info(CPU_t *cpu, char offset);
void sra_ind_reverse_info(CPU_t *cpu, char offset);
//core
void CPU_ED_opcode_run_reverse_info(CPU_t *cpu);
void CPU_CB_opcode_run_reverse_info(CPU_t *cpu);