#ifndef GUIDIALOG_H
#define GUIDIALOG_H

INT_PTR CALLBACK AboutDialogProc(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK BugReportDialogProc(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK ExportOSDialogProc(HWND, UINT, WPARAM, LPARAM);

#endif