import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(81B27D7E-B1B5-402f-84E5-0948A38D5497),
	pointer_default(unique),
]
interface IZ80Assembler : IDispatch
{
	[propget, helpstring("Output data from the assemble operation")]
	HRESULT Output([out, retval] IStream **Stream);

	[propput, helpstring("Input string for the assemble operation")]
	HRESULT Input([in] BSTR Input);
	
	/*
	[propget] HRESULT InputFile([out, retval] BSTR *FileName);
	[propput] HRESULT InputFile([in] BSTR FileName);

	[propget] HRESULT OutputFile([out, retval] BSTR *FileName);
	[propput] HRESULT OutputFile([in] BSTR FileName);

	HRESULT ClearDefines();
	HRESULT AddDefine([in] BSTR Name, [in] VARIANT Value);

	HRESULT ClearIncludeDirectories();
	HRESULT AddIncludeDirectory([in] BSTR Directory);
	*/

	HRESULT Assemble();
};

[
	uuid(36EB8341-0201-4ac6-A8D0-D06BC6E1B5E1),
	version(1.0),
]
library SPASM
{
	importlib("stdole32.tlb");

	[
		uuid(FD2AD3D2-78AE-4761-AD02-F8D9263A527D),
	]
	coclass CZ80Assembler
	{
		[default] interface IZ80Assembler;
	}
};
