// SPASMNew.idl : IDL source for SPASMNew
//

// This file will be processed by the MIDL tool to
// produce the type library (SPASMNew.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(38516350-2EF5-48DE-8C13-FEEAD1CAC91A),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IZ80Assembler : IDispatch
{
	[propget, helpstring("Output data from the assemble operation")]
	HRESULT Output([out, retval] IStream **Stream);

	[propput, helpstring("Input string for the assemble operation")]
	HRESULT Input([in] BSTR Input);

	HRESULT Assemble();
};
[
	uuid(16387CF3-1B28-46C0-ABA9-5DEC7A8FA7AA),
	version(1.0),
	helpstring("SPASM Z80 Assembler 1.0 Type Library"),
]
library SPASM
{
	importlib("stdole2.tlb");
	[
		uuid(BDD26FAE-A388-4860-9D4E-669809BC8EC2)		
	]
	coclass Z80Assembler
	{
		[default] interface IZ80Assembler;
	};
};

