enemy_health_abs = 0
enemy_flags_abs = 1
enemy_x_abs = 2
enemy_w_abs = 3
enemy_y_abs = 4
enemy_h_abs = 5
enemy_z_abs = 6
enemy_d_abs = 7
enemy_gen_abs = 8
enemy_com_ctr_abs = 9
enemy_com_ptr_abs = 10
enemy_anim_ctr_abs = 12
enemy_anim_ptr_abs = 13

object_ID_abs = 0
object_flags_abs = 1
object_x_abs = 2
object_w_abs = 3
object_y_abs = 4
object_h_abs = 5
object_z_abs = 6
object_d_abs = 7
object_anim_ctr_abs = 8
object_anim_ptr_abs = 9

misc_alive_abs = 0
misc_x_abs = 1
misc_w_abs = 2
misc_y_abs = 3
misc_h_abs = 4
misc_com_ptr_abs = 5
misc_code_abs = 5


animate_alive_abs = 0
animate_x_abs = 1
animate_w_abs = 2
animate_y_abs = 3
animate_h_abs = 4
animate_anim_ctr_abs = 5
animate_anim_ptr_abs = 6
animate_key_abs = 8
animate_anim_data_abs = 8